[package]
name = "bf_instrumentor"
version = "0.1.6"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.7.0"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
itertools = "0.10.3"